homepage_layout: page

title: The HEART of Therapy
email: bdalley@elliementalhealth.com
description: >- 
  A human-centered therapy site featuring the HEART documentation framework.
url: "https://bdalley1.github.io"
baseurl: "/heart-of-therapy"
github_username: bdalley1
minimal_mistakes_skin: default
search: true

# Theme setup
remote_theme: mmistakes/minimal-mistakes

markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: America/Denver

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache

author:
  name   : "Bryan Dalley, M.E.d., ACMHC"
  avatar : "/assets/images/bryan-photo.jpg"
  bio    : "Therapist, writer, human. I believe therapy—and notes—should feel human."
  links_label: "Contact Me"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:bdalley@elliementalhealth.com"

    - label: "Call Me"
      icon: "fas fa-phone"
      url: "tel:+18019603032"

    - label: "Text Me"
      icon: "fas fa-comment-dots"
      url: "sms:+18019603032"

      
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:bdalley@elliementalhealth.com"

    - label: "Call Me"
      icon: "fas fa-phone"
      url: "tel:+18019603032"

    - label: "Text Me"
      icon: "fas fa-comment-dots"
      url: "sms:+18019603032"

    - label: "X (Twitter)"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://twitter.com/bryan_dalley"

    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bryan-dalley-32b5ab369/"

    - label: "Psychology Today"
      icon: "fas fa-fw fa-user-md"
      url: "https://www.psychologytoday.com/us/therapists/bryan-dalley-provo-ut/1538539"


defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
